name: install/cache perl tools

inputs:
  tools:        { required: true,  type: string }
  install-base: { required: false, type: string }
  cache:        { required: false, type: string, default: yes }
  cache-gen:    { required: false, type: string, default: v1 }

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        case "${{ inputs.cache }}" in
          yes|workflow) cache="${{ inputs.cache }}" ;;
          *)            cache=no ;;
        esac
        tools="${{ inputs.tools }}"
        cache_gen="${{ inputs.cache-gen }}"
        install_base="${{ inputs.install-base }}"
        [[ "$install_base" =~ ^[^/] ]] && install_base="$HOME/$install_base"
        : ${install_base:=$HOME/perl5}
        echo "$install_base/bin" >> $GITHUB_PATH
        sed 's/^ *//' << END >> $GITHUB_ENV
          PERL5LIB=$install_base/lib/perl5${PERL5LIB:+:$PERL5LIB}
          PERL_LOCAL_LIB_ROOT=$install_base${PERL_LOCAL_LIB_ROOT:+:PERL_LOCAL_LIB_ROOT}
        END
        md5    /dev/null > /dev/null 2>&1 && md5=md5
        md5sum /dev/null > /dev/null 2>&1 && md5=md5sum
        test "md5" != ''
        hash=$( (perl -V; echo $tools) | $md5 | awk '{print $1}')
        [ "$cache_gen" != '' ] && hash="$hash-$cache_gen"
        [ "$cache" == workflow ] && hash="$hash-${{ github.run_id }}"
        echo "::set-output name=cache::$cache"
        echo "::set-output name=install-base::$install_base"
        echo "::set-output name=hash::$hash"
        perl -v
  
    - id: cache
      if: steps.setup.outputs.cache != 'no'
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup.outputs.install-base }}
        key:  ${{ steps.setup.outputs.hash }}
  
    - id: install-cpanminus
      shell: bash
      env:
        PERL_MB_OPT: --install_base ${{ steps.setup.outputs.install-base }}
        PERL_MM_OPT: INSTALL_BASE=${{ steps.setup.outputs.install-base }}
      run: |
        perl -MApp::cpanminus -E 'say "App::cpanminus is installed."' || \
          curl -sL http://cpanmin.us | perl - -n App::cpanminus
  
    - id: install
      if: inputs.tools != ''
      shell: bash
      env:
        PERL_MB_OPT: --install_base ${{ steps.setup.outputs.install-base }}
        PERL_MM_OPT: INSTALL_BASE=${{ steps.setup.outputs.install-base }}
      run: |
        cpanm -n $(echo "${{ inputs.tools }}")
