name: install/cache perl modules

inputs:
  modules:      { required: true,  type: string }
  install_base: { required: false, type: string }
  cache:        { required: false, type: boolean, default: true }
  cache_gen:    { required: false, type: string,  default: v1 }
  unique:       { required: false, type: boolean, default: false }

runs:
  using: composite
  steps:

    - name: setup
      id: setup
      shell: bash
      run: |
        modules="${{ inputs.modules }}"
        cache_gen="${{ inputs.cache_gen }}"
        install_base="${{ inputs.install_base }}"
        [[ "$install_base" =~ ^[^/] ]] && install_base="$HOME/$install_base"
        : ${install_base:=$HOME/perl5}
        echo "$install_base/bin" >> $GITHUB_PATH
        sed 's/^ *//' << END >> $GITHUB_ENV
          PERL_MB_OPT=--install_base "$install_base"
          PERL_MM_OPT=INSTALL_BASE=$install_base
          PERL5LIB=$install_base/lib/perl5${PERL5LIB:+:$PERL5LIB}
          PERL_LOCAL_LIB_ROOT=$install_base${PERL_LOCAL_LIB_ROOT:+:PERL_LOCAL_LIB_ROOT}
        END
        hash=$( (perl -V; echo $cache_gen $modules) | md5sum | awk '{print $1}')
        [ "${{ inputs.unique }}" == 'true' ] && hash=$hash-${{ github.run_id }}
        echo "::set-output name=install_base::$install_base"
        echo "::set-output name=hash::$hash"
        perl -v
  
    - name: cache
      if: inputs.cache == 'true'
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup.outputs.install_base }}
        key:  ${{ steps.setup.outputs.hash }}
  
    - name: install cpanminus
      shell: bash
      run: |
        perl -MApp::cpanminus -E 'say "App::cpanminus is installed."' || \
          curl -sL http://cpanmin.us | perl - -n App::cpanminus
  
    - name: install modules
      if: ${{ inputs.modules != '' }}
      shell: bash
      run: |
        cpanm -n ${{ inputs.modules }}
