name: install/cache perl tools

inputs:
  tools:        { required: true,  type: string }
  install_base: { required: false, type: string }
  cache:        { required: false, type: string, default: yes }
  cache_gen:    { required: false, type: string, default: v1 }
  perl-version: { required: false, type: string }

outputs:
  cache-hit:
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - name: install perl
      if: inputs.perl-version != ''
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ inputs.perl-version }}
  
    - id: setup
      shell: bash
      run: |
        case "${{ inputs.cache }}" in
          yes|workflow) cache="${{ inputs.cache }}" ;;
          *) cache='' ;;
        esac
        tools="${{ inputs.tools }}"
        cache_gen="${{ inputs.cache_gen }}"
        install_base="${{ inputs.install_base }}"
        [[ "$install_base" =~ ^[^/] ]] && install_base="$HOME/$install_base"
        : ${install_base:=$HOME/perl5}
        echo "$install_base/bin" >> $GITHUB_PATH
        sed 's/^ *//' << END >> $GITHUB_ENV
          PERL_MB_OPT=--install_base "$install_base"
          PERL_MM_OPT=INSTALL_BASE=$install_base
          PERL5LIB=$install_base/lib/perl5${PERL5LIB:+:$PERL5LIB}
          PERL_LOCAL_LIB_ROOT=$install_base${PERL_LOCAL_LIB_ROOT:+:PERL_LOCAL_LIB_ROOT}
        END
        hash=$( (perl -V; echo $tools) | md5sum | awk '{print $1}')
        [ "$cache_gen" != '' ] && hash="$hash-$cache_gen"
        [ "$cache" == workflow ] && hash="$hash-${{ github.run_id }}"
        echo "::set-output name=cache::$cache"
        echo "::set-output name=install_base::$install_base"
        echo "::set-output name=hash::$hash"
        perl -v
  
    - id: cache
      if: steps.setup.outputs.cache != ''
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup.outputs.install_base }}
        key:  ${{ steps.setup.outputs.hash }}
  
    - name: install cpanminus
      shell: bash
      run: |
        perl -MApp::cpanminus -E 'say "App::cpanminus is installed."' || \
          curl -sL http://cpanmin.us | perl - -n App::cpanminus
  
    - name: install tools
      if: inputs.tools != ''
      shell: bash
      run: |
        cpanm -n ${{ inputs.tools }}
