name: install/cache perl tools

inputs:
  tools:     { required: true,  type: string }
  cache:     { required: false, type: string, default: yes }
  sudo:      { required: false, type: boolean, default: false }
  key:       { required: false, type: string }

outputs:
  cache-hit:
    value: ${{ steps.update.outputs.cache-hit }}

runs:
  using: composite
  steps:

    - id: setup
      shell: bash
      run: |
        : setup use-perl-tools
        case "${{ inputs.cache }}" in
            yes|workflow) cache="${{ inputs.cache }}" ;;
            *)            cache=no ;;
        esac
        tools="${{ inputs.tools }}"
        [ "${{ inputs.sudo }}" == 'true' ] && sudo=sudo
        given_key="${{ inputs.key }}"
        version_key="$( perl -V | (md5sum||md5) | awk '{print $1}' )"
        key="${given_key:+$given_key-}${version_key}"
        local_base="$HOME/perl5"
        mkdir -p $local_base/{bin,lib/perl5}
        bin="$local_base/bin"
        if [[ ! "$PATH" =~ $bin ]]
        then
            export PATH="$local_base/bin:$PATH"
            echo "$local_base/bin" >> $GITHUB_PATH
        fi
        lib="$local_base/lib/perl5"
        if [[ ! "$PERL5LIB" =~ $lib ]]
        then
            export PERL5LIB="$lib${PERL5LIB:+:$PERL5LIB}"
            export PERL_LOCAL_LIB_ROOT="$local_base${PERL_LOCAL_LIB_ROOT:+:$PERL_LOCAL_LIB_ROOT}"
            echo "PERL5LIB=$PERL5LIB"                       >> $GITHUB_ENV
            echo "PERL_LOCAL_LIB_ROOT=$PERL_LOCAL_LIB_ROOT" >> $GITHUB_ENV
        fi
        install_base="$( perl -E 'print join " ", @INC, split(/:+/, $ENV{PATH})' )"
        cat << END
        ::set-output name=cache::$cache
        ::set-output name=perl::${sudo:+$sudo }perl
        ::set-output name=key::$key
        ::set-output name=command::${sudo:+$sudo }cpanm -n
        ::set-output name=install_base::$install_base
        END
        perl -V
  
    - id: install-cpanminus
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   cpanm --version || curl -sL https://cpanmin.us | ${{ steps.setup.outputs.perl }} - -n -v
        directory: ${{ steps.setup.outputs.install_base }}
        key:       ${{ steps.setup.outputs.key }}
        target:    App::cpanminus
        cache:     ${{ inputs.cache }}
  
    - id: check-cpanminus
      shell: bash
      run: |
        if cpanm --version
        then
          which cpanm
        else
          path=$(perldoc -lm App::cpanminus)
          if [[ "$path" =~ ^(.*)/lib/ ]]
          then
            bin=${BASH_REMATCH[1]}/bin
            cpanm=$bin/cpanm
            [ -x $cpanm ] && echo $bin >> $GITHUB_PATH
          fi
        fi

    - id: update
      uses: office-tecoli/actions-install-and-cache@v0
      with:
        command:   ${{ steps.setup.outputs.command }}
        directory: ${{ steps.setup.outputs.install_base }}
        key:       ${{ steps.setup.outputs.key }}
        target:    ${{ inputs.tools }}
        cache:     ${{ inputs.cache }}
