name: install/cache perl modules

inputs:
  modules:   { required: true,  type: string }
  install:   { required: false, type: string }
  cache:     { required: false, type: string, default: yes }
  cache_gen: { required: false, type: string, default: v1 }
  clean:     { required: false, type: boolean, default: false }

runs:
  using: composite
  steps:

    - name: setup
      id: setup
      shell: bash
      run: |
        modules="${{ inputs.modules }}"
        cache_gen="${{ inputs.cache_gen }}"
        install="${{ inputs.install }}"
        [[ "$install" =~ ^[^/] ]] && install="$HOME/$install"
        : ${install:=$HOME/perl5}
        echo "$install/bin" >> $GITHUB_PATH
        sed 's/^ *//' << END >> $GITHUB_ENV
          PERL_MB_OPT=--install_base "$install"
          PERL_MM_OPT=INSTALL_BASE=$install
          PERL5LIB=$install/lib/perl5${PERL5LIB:+:$PERL5LIB}
          PERL_LOCAL_LIB_ROOT=$install${PERL_LOCAL_LIB_ROOT:+:PERL_LOCAL_LIB_ROOT}
        END
        hash=$( (perl -V; echo $cache_gen $modules) | md5sum | awk '{print $1}')
        [ "${{ inputs.clean }}" == 'true' ] && hash=$hash-${{ github.run_id }}
        echo "::set-output name=install::$install"
        echo "::set-output name=hash::$hash"
        perl -v
  
    - name: cache
      if: inputs.cache == 'yes'
      uses: actions/cache@v2
      with:
        path: ${{ steps.setup.outputs.install }}
        key:  ${{ steps.setup.outputs.hash }}
  
    - name: install cpanminus
      shell: bash
      run: |
        install="${{ steps.setup.outputs.install }}"
        perl -MApp::cpanminus -E 'say "App::cpanminus is installed."' || \
          curl -sL http://cpanmin.us | perl - -n App::cpanminus
  
    - name: install modules
      if: ${{ inputs.modules != '' }}
      shell: bash
      run: |
        install="${{ steps.setup.outputs.install }}"
        cpanm -n ${{ inputs.modules }}
