name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          modules: Acme
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          modules: Acme
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: no
          modules: Acme
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  install-dir:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: echo "::set-output name=home::$HOME"
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          modules: Acme
          install_base: ${{ steps.setup.outputs.home }}/perl
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  relative-install-dir:
    needs: install-dir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          modules: Acme
          install_base: perl
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          modules: Acme
          cache_gen: v2
      - run: perl -MAcme -E 'say "Acme!"'
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
