name: test

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
  workflow_dispatch:

jobs:
  initial:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  cached:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  no-cache:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: no
          tools: App::ansiecho
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  install-dir:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - id: setup
        run: echo "::set-output name=home::$HOME"
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
          install_base: ${{ steps.setup.outputs.home }}/perl
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  relative-install-dir:
    needs: install-dir
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
          install_base: perl
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
  cache-gen:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
          cache_gen: v2
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  perl-version:
    needs: initial
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
          cache_gen: v2
          perl-version: '5.18'
      - run: perl -v
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" != true
  perl-version-cached:
    needs: perl-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: action
        with:
          cache: workflow
          tools: App::ansiecho
          cache_gen: v2
          perl-version: '5.18'
      - run: perl -v
      - run: ansiecho -C '555/(132,0,41)' d i g i t a l
      - run: test "${{ steps.action.outputs.cache-hit }}" == true
